language: ruby
dist: trusty
rvm:
  - 2.4.1
branches:
  only:
    - master
jobs:
  include:
    - stage: rubocop
      script: "bundle exec rubocop"
    - stage: rspec
      script: "bundle exec rspec"
