language: ruby
dist: trusty
cache: bundler
services:
  - postgresql
rvm:
  - 2.4.1
branches:
  only:
    - master
jobs:
  include:
    - stage: rubocop
      script: "bundle exec rubocop"
    - stage: rspec
      before_script:
        - psql -c 'create database carchain_test;' -U postgres
      script: "bundle exec rspec"
