default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['CARCHAIN_DATABASE_HOST'] || 'localhost' %>
  port: <%= (ENV['CARCHAIN_DATABASE_PORT'] || 5432).to_i %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: adminPassword

development:
  <<: *default
  database: carchain_dev

test:
  <<: *default
  database: carchain_test

production:
  <<: *default
  database: carchain_prod
  password: <%= ENV['CARCHAIN_DATABASE_PASSWORD'] %>
